require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FilersController do

  # This should return the minimal set of attributes required to create a valid
  # Filer. As you add validations to Filer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name_prefix" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FilersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all filers as @filers" do
      filer = Filer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:filers).should eq([filer])
    end
  end

  describe "GET show" do
    it "assigns the requested filer as @filer" do
      filer = Filer.create! valid_attributes
      get :show, {:id => filer.to_param}, valid_session
      assigns(:filer).should eq(filer)
    end
  end

  describe "GET new" do
    it "assigns a new filer as @filer" do
      get :new, {}, valid_session
      assigns(:filer).should be_a_new(Filer)
    end
  end

  describe "GET edit" do
    it "assigns the requested filer as @filer" do
      filer = Filer.create! valid_attributes
      get :edit, {:id => filer.to_param}, valid_session
      assigns(:filer).should eq(filer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filer" do
        expect {
          post :create, {:filer => valid_attributes}, valid_session
        }.to change(Filer, :count).by(1)
      end

      it "assigns a newly created filer as @filer" do
        post :create, {:filer => valid_attributes}, valid_session
        assigns(:filer).should be_a(Filer)
        assigns(:filer).should be_persisted
      end

      it "redirects to the created filer" do
        post :create, {:filer => valid_attributes}, valid_session
        response.should redirect_to(Filer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filer as @filer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filer.any_instance.stub(:save).and_return(false)
        post :create, {:filer => { "name_prefix" => "invalid value" }}, valid_session
        assigns(:filer).should be_a_new(Filer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filer.any_instance.stub(:save).and_return(false)
        post :create, {:filer => { "name_prefix" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested filer" do
        filer = Filer.create! valid_attributes
        # Assuming there are no other filers in the database, this
        # specifies that the Filer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Filer.any_instance.should_receive(:update_attributes).with({ "name_prefix" => "MyString" })
        put :update, {:id => filer.to_param, :filer => { "name_prefix" => "MyString" }}, valid_session
      end

      it "assigns the requested filer as @filer" do
        filer = Filer.create! valid_attributes
        put :update, {:id => filer.to_param, :filer => valid_attributes}, valid_session
        assigns(:filer).should eq(filer)
      end

      it "redirects to the filer" do
        filer = Filer.create! valid_attributes
        put :update, {:id => filer.to_param, :filer => valid_attributes}, valid_session
        response.should redirect_to(filer)
      end
    end

    describe "with invalid params" do
      it "assigns the filer as @filer" do
        filer = Filer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filer.any_instance.stub(:save).and_return(false)
        put :update, {:id => filer.to_param, :filer => { "name_prefix" => "invalid value" }}, valid_session
        assigns(:filer).should eq(filer)
      end

      it "re-renders the 'edit' template" do
        filer = Filer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filer.any_instance.stub(:save).and_return(false)
        put :update, {:id => filer.to_param, :filer => { "name_prefix" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filer" do
      filer = Filer.create! valid_attributes
      expect {
        delete :destroy, {:id => filer.to_param}, valid_session
      }.to change(Filer, :count).by(-1)
    end

    it "redirects to the filers list" do
      filer = Filer.create! valid_attributes
      delete :destroy, {:id => filer.to_param}, valid_session
      response.should redirect_to(filers_url)
    end
  end

end
